"""reward_model.py — Small local reward model for Enhinged V2 RLHF.

Architecture: the base HinglishGPT transformer (already bilingual-capable,
already with the right tokenizer/vocab) with the language-modeling head
replaced by a single scalar output head. This reuses code that's already
known to work and avoids introducing a separate model family.

Training objective: Bradley-Terry pairwise loss on (winner, loser) pairs
generated by the AI judge (see label_preference_data.py).

Usage:
    # Training
    python reward_model.py --base_ckpt checkpoints/best.pt \
                           --pref_data pref_data/judge_pairs.jsonl \
                           --out_dir checkpoints/reward_model/

    # Evaluation on held-out split
    python reward_model.py --base_ckpt checkpoints/best.pt \
                           --pref_data pref_data/judge_pairs.jsonl \
                           --out_dir checkpoints/reward_model/ \
                           --mode eval
"""

from __future__ import annotations

import argparse
import json
import math
import os
import random
from typing import Optional

import torch
import torch.nn as nn
from torch.nn import functional as F

from config import GPTConfig, DEFAULT_TOKENIZER_NAME
from model import HinglishGPT, load_model_from_checkpoint


class RewardModel(nn.Module):
    """Wraps HinglishGPT backbone with a scalar value head.

    The LM head is replaced by a linear projection to a single scalar.
    The backbone transformer weights can be initialized from a pretrained
    checkpoint (recommended) or from scratch.
    """

    def __init__(self, config: GPTConfig) -> None:
        super().__init__()
        # Backbone: shared HinglishGPT transformer (no LM head).
        self.transformer = HinglishGPT(config).transformer
        self.ln_f = HinglishGPT(config).transformer["ln_f"]  # aliased for clarity
        self.config = config
        # Scalar value head: projects from n_embd to 1.
        self.value_head = nn.Linear(config.n_embd, 1, bias=False)
        nn.init.normal_(self.value_head.weight, mean=0.0, std=0.01)

    def forward(self, idx: torch.Tensor) -> torch.Tensor:
        """Return a scalar reward score for each sequence in the batch.

        Args:
            idx: (batch, seq_len) token indices

        Returns:
            rewards: (batch,) scalar reward for each sequence
        """
        _, sequence_length = idx.shape
        if sequence_length > self.config.block_size:
            idx = idx[:, -self.config.block_size:]
            sequence_length = self.config.block_size

        positions = torch.arange(sequence_length, device=idx.device)
        x = self.transformer["drop"](
            self.transformer["wte"](idx) + self.transformer["wpe"](positions)
        )
        for block in self.transformer["h"]:
            x, _ = block(x)
        x = self.transformer["ln_f"](x)

        # Pool by taking the last token's hidden state (GPT-style pooling).
        reward = self.value_head(x[:, -1, :]).squeeze(-1)  # (batch,)
        return reward

    @classmethod
    def from_pretrained_backbone(cls, ckpt_path: str, device: Optional[torch.device] = None) -> "RewardModel":
        """Initialize reward model backbone from a HinglishGPT checkpoint."""
        resolved_device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")
        try:
            checkpoint = torch.load(ckpt_path, map_location=resolved_device, weights_only=False)
        except TypeError:
            checkpoint = torch.load(ckpt_path, map_location=resolved_device)

        config = GPTConfig(**checkpoint["model_config"])
        rm = cls(config)

        # Load backbone weights, skipping lm_head (we replace it with value_head).
        backbone_state = {
            k: v for k, v in checkpoint["model_state"].items()
            if not k.startswith("lm_head.") and not k.startswith("value_head.")
        }
        # Map HinglishGPT keys -> RewardModel keys (both share "transformer." prefix).
        missing, unexpected = rm.load_state_dict(backbone_state, strict=False)
        print(f"RewardModel loaded backbone from {ckpt_path}")
        if missing:
            non_value = [k for k in missing if "value_head" not in k]
            if non_value:
                print(f"  WARNING: Missing keys (non-value-head): {non_value[:10]}")
        rm.to(resolved_device)
        return rm

    def save(self, path: str) -> None:
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        torch.save({
            "model_state": self.state_dict(),
            "model_config": {
                "block_size": self.config.block_size,
                "vocab_size": self.config.vocab_size,
                "n_layer": self.config.n_layer,
                "n_head": self.config.n_head,
                "n_embd": self.config.n_embd,
                "dropout": self.config.dropout,
                "bias": self.config.bias,
            }
        }, path)
        print(f"RewardModel saved to {path}")

    @classmethod
    def load(cls, path: str, device: Optional[torch.device] = None) -> "RewardModel":
        resolved_device = device or torch.device("cuda" if torch.cuda.is_available() else "cpu")
        try:
            ckpt = torch.load(path, map_location=resolved_device, weights_only=False)
        except TypeError:
            ckpt = torch.load(path, map_location=resolved_device)
        rm = cls(GPTConfig(**ckpt["model_config"]))
        rm.load_state_dict(ckpt["model_state"])
        rm.to(resolved_device)
        rm.eval()
        return rm


def _bradley_terry_loss(score_w: torch.Tensor, score_l: torch.Tensor) -> torch.Tensor:
    """Pairwise (Bradley-Terry) loss: -log(sigmoid(score_winner - score_loser)).

    This is the standard reward model training loss from InstructGPT.
    score_w, score_l: (batch,) scalars for winner and loser completions.
    """
    return -F.logsigmoid(score_w - score_l).mean()


def _encode_pair(enc, prompt: str, completion: str, block_size: int, device: torch.device) -> torch.Tensor:
    """Encode prompt + completion into token IDs, truncated to block_size."""
    text = f"User: {prompt}\nAssistant: {completion}"
    ids = enc.encode(text)[-block_size:]
    return torch.tensor(ids, dtype=torch.long, device=device).unsqueeze(0)


def train_reward_model(
    reward_model: RewardModel,
    pref_data: list[dict],
    device: torch.device,
    learning_rate: float = 1e-4,
    max_iters: int = 1000,
    batch_size: int = 8,
    val_split: float = 0.1,
    out_dir: str = "checkpoints/reward_model",
) -> None:
    """Train the reward model on pairwise preference data.

    pref_data format: list of dicts with keys:
        prompt:  str
        winner:  str  (preferred completion)
        loser:   str  (dispreferred completion)
    """
    import tiktoken
    enc = tiktoken.get_encoding(DEFAULT_TOKENIZER_NAME)

    random.shuffle(pref_data)
    n_val = max(1, int(len(pref_data) * val_split))
    val_data = pref_data[:n_val]
    train_data = pref_data[n_val:]

    print(f"Training reward model: {len(train_data)} train pairs, {len(val_data)} val pairs")

    optimiser = torch.optim.AdamW(reward_model.parameters(), lr=learning_rate, weight_decay=0.01)
    reward_model.train()
    reward_model.to(device)

    best_val_acc = 0.0
    os.makedirs(out_dir, exist_ok=True)

    for iteration in range(max_iters):
        # Sample a mini-batch of pairs.
        batch = random.choices(train_data, k=batch_size)
        loss = torch.tensor(0.0, device=device, requires_grad=True)
        for pair in batch:
            prompt = pair["prompt"]
            w_ids = _encode_pair(enc, prompt, pair["winner"], reward_model.config.block_size, device)
            l_ids = _encode_pair(enc, prompt, pair["loser"], reward_model.config.block_size, device)
            score_w = reward_model(w_ids)
            score_l = reward_model(l_ids)
            loss = loss + _bradley_terry_loss(score_w, score_l)
        loss = loss / batch_size

        optimiser.zero_grad()
        loss.backward()
        nn.utils.clip_grad_norm_(reward_model.parameters(), 1.0)
        optimiser.step()

        if (iteration + 1) % 100 == 0 or iteration == 0:
            # Evaluate agreement with judge on held-out val split.
            val_acc = evaluate_reward_model(reward_model, val_data, enc, device)
            print(f"  iter {iteration + 1:4d} | train_loss {loss.item():.4f} | val_agreement {val_acc:.3f}")
            if val_acc > best_val_acc:
                best_val_acc = val_acc
                reward_model.save(os.path.join(out_dir, "best_reward_model.pt"))
                print(f"    → Saved best reward model (val_agreement={best_val_acc:.3f})")

    print(f"\nReward model training complete. Best val agreement: {best_val_acc:.3f}")
    if best_val_acc < 0.60:
        print("WARNING: Val agreement < 60% — reward model may not be reliable for PPO.")
        print("Consider more labeling data, more training iters, or revisiting the judge prompt.")
    else:
        print("Val agreement >= 60% — reward model is suitable for PPO.")


@torch.no_grad()
def evaluate_reward_model(
    reward_model: RewardModel,
    val_data: list[dict],
    enc,
    device: torch.device,
) -> float:
    """Return fraction of val pairs where reward model agrees with judge ranking."""
    reward_model.eval()
    correct = 0
    for pair in val_data:
        prompt = pair["prompt"]
        w_ids = _encode_pair(enc, prompt, pair["winner"], reward_model.config.block_size, device)
        l_ids = _encode_pair(enc, prompt, pair["loser"], reward_model.config.block_size, device)
        score_w = reward_model(w_ids).item()
        score_l = reward_model(l_ids).item()
        if score_w > score_l:
            correct += 1
    reward_model.train()
    return correct / max(1, len(val_data))


def main() -> None:
    parser = argparse.ArgumentParser(description="Train or evaluate the Enhinged V2 reward model.")
    parser.add_argument("--mode", choices=["train", "eval"], default="train")
    parser.add_argument("--base_ckpt", required=True, help="Path to phase-1 HinglishGPT checkpoint.")
    parser.add_argument("--pref_data", required=True, help="Path to JSONL preference dataset.")
    parser.add_argument("--out_dir", default="checkpoints/reward_model")
    parser.add_argument("--reward_ckpt", default=None, help="Reward model checkpoint for eval mode.")
    parser.add_argument("--learning_rate", type=float, default=1e-4)
    parser.add_argument("--max_iters", type=int, default=1000)
    parser.add_argument("--batch_size", type=int, default=8)
    parser.add_argument("--val_split", type=float, default=0.1)
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # Load preference data.
    with open(args.pref_data, "r", encoding="utf-8") as f:
        pref_data = [json.loads(line) for line in f if line.strip()]
    print(f"Loaded {len(pref_data)} preference pairs from {args.pref_data}")

    if args.mode == "train":
        rm = RewardModel.from_pretrained_backbone(args.base_ckpt, device=device)
        train_reward_model(
            rm, pref_data, device,
            learning_rate=args.learning_rate,
            max_iters=args.max_iters,
            batch_size=args.batch_size,
            val_split=args.val_split,
            out_dir=args.out_dir,
        )
    else:
        if not args.reward_ckpt:
            args.reward_ckpt = os.path.join(args.out_dir, "best_reward_model.pt")
        rm = RewardModel.load(args.reward_ckpt, device=device)
        import tiktoken
        enc = tiktoken.get_encoding(DEFAULT_TOKENIZER_NAME)
        import random
        random.shuffle(pref_data)
        n_val = max(1, int(len(pref_data) * 0.1))
        val_data = pref_data[:n_val]
        acc = evaluate_reward_model(rm, val_data, enc, device)
        print(f"Held-out agreement with judge: {acc:.3f} ({int(acc * len(val_data))}/{len(val_data)} correct)")


if __name__ == "__main__":
    main()
